name: Java CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        # https://endoflife.date/java
        java-version: [8, 11, 17, 20]

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
      - name: Test with Coverage
        uses: gradle/gradle-build-action@v2
        with:
          arguments: koverXmlReport
      - name: Upload coverage to Codecov
        if: ${{ matrix.java-version == '20' && matrix.os == 'ubuntu-latest' }}
        uses: codecov/codecov-action@v3
