name: Java CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        # https://endoflife.date/java
        # Gradle needs to be able to run on it: https://docs.gradle.org/current/userguide/compatibility.html?#java
        java-version: [8, 11, 17, 21]

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'corretto'
      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v3
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Build with Gradle
        run: ./gradlew assemble
      - name: Test with Coverage
        run: ./gradlew koverXmlReport
      - name: Upload coverage to Codecov
        if: ${{ matrix.java-version == '21' && matrix.os == 'ubuntu-latest' }}
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
